### ISSUE TITLE
[BUG]: Helm chart missing websocket ingress template

### ISSUE THREAD

**Issue by jackrh** [keephq/helm-charts#11]
### Description of the bug

If you add an ingress to websocket in your values.yaml it will never render the necessary yaml because the websocket template file is missing.

### Steps To Reproduce

1. Add ingress to values.yaml file for websocket
 
```
websocket:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: keep-websocket.${SECRET_DOMAIN}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - keep-websocket.${SECRET_DOMAIN}

```
2. Install helm chart
3. Verify no ingress is created
