### ISSUE TITLE
[BUG]: Frontend 404 with Traefik

### ISSUE THREAD

**Issue by nlamirault** [keephq/helm-charts#121]
### Description of the bug

Hi, using the Helm chart to deploy Keep with the ingress controller Traefik I've got this generated ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: alerting-strip-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/timeouts.connect: 3600s
    traefik.ingress.kubernetes.io/timeouts.idle: 3600s
    traefik.ingress.kubernetes.io/timeouts.read: 3600s
    traefik.ingress.kubernetes.io/timeouts.write: 3600s
    traefik.ingress.kubernetes.io/websockets.enabled: 'true'
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: keep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keep
    app.kubernetes.io/part-of: keep
    app.kubernetes.io/version: 0.34.5
    argocd.argoproj.io/instance: keep
    helm.sh/chart: keep-0.1.59
  name: keep-ingress
  namespace: alerting
spec:
  ingressClassName: traefik
  rules:
    - host: keep.192.168.0.61.nip.io
      http:
        paths:
          - backend:
              service:
                name: keep-websocket
                port:
                  number: 6001
            path: /websocket
            pathType: Prefix
          - backend:
              service:
                name: keep-backend
                port:
                  number: 8080
            path: /v2
            pathType: Prefix
          - backend:
              service:
                name: keep-frontend
                port:
                  number: 3000
            path: /
            pathType: Prefix
```

But i've got a `404`.
If i remove the annotation `traefik.ingress.kubernetes.io/router.middlewares: alerting-strip-prefix@kubernetescrd` , the frontend works fine.

### Steps To Reproduce

Install Keep using Helm and enable ingress:

```yaml
  global:
    ingress:
      enabled: true
      className: traefik
      hosts:
      - host: keep.192.168.0.61.nip.io
```

**Comment by nlamirault** [comment]
Kubernetes CRD must be enabled in Traefik deployment. 
Ex in Helm values file:

```yaml
providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true
    kubernetesGateway:
      enabled: true
```
