### ISSUE TITLE
[FEAT]: Keep HelmChart 0.1.14 

### ISSUE THREAD

**Issue by bimax** [keephq/helm-charts#46]
### Description

Struggling to run keep application in the k8s cluster.

Values file description is limited so I can't get sense of what should be configured. 
Extra confusion I am getting from the readme: https://github.com/keephq/helm-charts/blob/main/README.md
In Configuration section I can see usage for frontend.publicApiUrl and frontend.internalApiUrl but I can't see this values in any of helm templates.

Also there is different port-forwarding configuration in the [README](https://github.com/keephq/helm-charts/blob/main/README.md) of a chart and in documentation [kubernetes](https://github.com/keephq/keep/blob/main/docs/deployment/kubernetes.mdx) so which ports have to be forwarded?

### Additional Information

My current values looks like:
```
    namespace: mmaximov-dev
    backend:
      waitForDatabase: false
      env:
      - name: DATABASE_CONNECTION_STRING
        value: mysql+pymysql://dashboard_rw:[********]@ams-vm40.hostname.net:3306/alerts_dashboard
      - name: PUSHER_HOST
        value: dev-keep-websocket.mmaximov-dev.svc.ams-eng-prod.local
      healthCheck:
        enabled: true
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: '1'
          memory: 3Gi
      healthCheck:
        enabled: true
      ingress:
        className: haproxy
    frontend:
      publicApiUrl:
      internalApiUrl: http://dev-keep-backend:8080
      env:
      - name: API_URL
        value: http://dev-keep-backend:8080
      - name: PUSHER_HOST
        value: dev-keep-websocket.mmaximov-dev.svc.ams-eng-prod.local
      ingress:
        className: haproxy-rfissl
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: '1'
          memory: 3Gi
    database:
      enabled: false
```
